name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'
    
    - name: Cache Julia packages
      uses: julia-actions/cache@v1
    
    - name: Install dependencies
      run: |
        julia --project=. -e 'using Pkg; Pkg.instantiate()'
    
    - name: Check Metal availability
      run: |
        julia -e 'using Metal; println("Metal functional: ", Metal.functional())'
    
    - name: Run tests
      run: |
        julia --project=. test/runtests.jl
      env:
        JULIA_NUM_THREADS: auto

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'
        
    - name: Check code format
      run: |
        julia -e 'using Pkg; Pkg.add("JuliaFormatter"); using JuliaFormatter; format_text(read("metal_bandit_simulator.jl", String)) |> print'